name: Deploy Up-Skill

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      - name: Disable host key checking
        run: |
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Deploy
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'

          echo "Updating Backend"
          cd /var/www/up-skill/backend
          git pull origin main
          npm install
          pm2 restart upskill-server || pm2 start src/server.js --name upskill-server

          echo "Updating Admin Dashboard"
          cd /var/www/up-skill/frontend
          git pull origin main
          npm install
          npm run build
          pm2 restart upskill-admin || pm2 start npm --name upskill-admin -- start

          echo "Updating Frontend"
          cd /var/www/up-skill/client-frontend
          git pull origin main
          npm install
          npm run build
          pm2 restart upskill-client || pm2 start npm --name upskill-client -- start

          echo "Deploy complete âœ…"
          EOF
